php-version = "8.0"

[source]
paths = ["src", "tests"]
includes = ["vendor"]
excludes = ["src/js"]

[analyzer]
find-unused-expressions = true
find-unused-definitions = true
analyze-dead-code = true
check-throws = true
check-missing-override = true
find-unused-parameters = true
check-missing-type-hints = true
check-closure-missing-type-hints = true
check-arrow-function-missing-type-hints = true
enforce-class-finality = true
require-api-or-internal = true
